### ISSUE TITLE
Add ability to upgrade universal forwarders and servers

### ISSUE THREAD

**Issue by ITBlogger** [voxpupuli/puppet-splunk#1]
Hi SETeam,

Thanks for creating this very useful puppet module.

I'm trying to modify the module so that it will upgrade universal forwarders to the latest version and can't get it to work right, so I was hoping that I could get help with that or get that functionality added to the module.

Thanks,

Alex

**Comment by crayfishx** [comment]
This is a very old issue and seems to be solved with the introduction of `forwarder_pkg_ensure` in the `splunk::forwarder` class so I'm closing this.  Feel free to re-open if this is still an issue.  Thanks
