### ISSUE TITLE
Error: Failed to apply catalog: Found 1 dependency cycle:

### ISSUE THREAD

**Issue by jkarns87** [voxpupuli/puppet-splunk#106]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: PE 2017.1
- Ruby: ruby-2.0.0.648
- Distribution: RHEL 7.3
- Module version: 2017-01-12 - Release 5.1.0

## How to reproduce (e.g Puppet code you use)
class profile::splunk_forwarder {
  include ::splunk::forwarder
}

splunk::params::src_root: 'puppet:///software'
splunk::params::version: '6.5.1'
splunk::params::build: 'f74036626f0c'
splunk::forwarder::forwarder_output:
  'tcpout_defaultgroup':
    section: 'default'
    setting: 'defaultGroup'
    value: 'default-autolb-group'
    tag: 'splunk_forwarder'
  'tcpout_default-autolb-group':
    section: 'tcpout:default-autolb-group'
    setting: 'server'
    value: '<servers>'
    tag: 'splunk_forwarder'

## What are you seeing
Error: Failed to apply catalog: Found 1 dependency cycle:
(File[/opt/staging/splunk/splunkforwarder-6.5.1-f74036626f0c-linux-2.6-x86_64.rpm] => Staging::File[splunkforwarder-6.5.1-f74036626f0c-linux-2.6-x86_64.rpm] => Package[splunkforwarder] => File[/opt/staging/splunk/splunkforwarder-6.5.1-f74036626f0c-linux-2.6-x86_64.rpm])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz

## What behaviour did you expect instead
Splunk Forwarder should install from the software location served from my puppet master and then outputs should be configured.

**Comment by starchx** [comment]
Just ran into same issue, and my fix is to avoid using **splunk_forwarder** as profile name. Apparently this will generate a tag which then conflicts with the dependency setup in the module. Hope this helps someone.

**Comment by TraGicCode** [comment]
Thanks @starchx for the information on why this happens!
