### ISSUE TITLE
Windows File paths must be fully qualified

### ISSUE THREAD

**Issue by roberteckdale** [voxpupuli/puppet-splunk#115]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)
```
class { '::splunk::params':
        version           => '6.6.1',
        build             => 'aeae3fe0c5af',
        server            => 'splunk.acme.local',
      }
include ::splunk
```

## What are you seeing
Puppet run throws the following error:
Failed to apply catalog: Parameter path failed on File[/opt/splunk/etc/system/local/authentication.conf]: File paths must be fully qualified, not '/opt/splunk/etc/system/local/authentication.conf' at /etc/puppetlabs/code/environments/production/modules/splunk/manifests/init.pp:221

Looks like the module maybe isn't intended to install Splunk (versus Forwarder) in Windows?

**Comment by TraGicCode** [comment]
I will verify this Tommorow morning to see if this is still an issue with the latest.
