### ISSUE TITLE
splunkforwarder_server not working

### ISSUE THREAD

**Issue by TraGicCode** [voxpupuli/puppet-splunk#121]
When trying to use splunkforwarder_server type i get the following error on both ubuntu 16.04 and windows 2016

```
Error: /Stage[main]/Profile::Linux::Splunk::Universalforwarder/Splunkforwarder_server[sslConfig/sslPassword]: Could not evaluate: file_path must be set with splunk_config type before provider can be used
Notice: /Stage[main]/Splunk::Virtual/Service[splunk]: Dependency Splunkforwarder_server[sslConfig/sslPassword] has failures: true
Warning: /Stage[main]/Splunk::Virtual/Service[splunk]: Skipping because of failed dependencies
```

Here is the code i'm using

```
  splunkforwarder_server { 'sslConfig/sslPassword':
    value   => '$1$Bj3FSJRCLtSH',
    tag   => 'splunk_forwarder'
  }
```

@nicholaspearson

**Comment by nicholaspearson** [comment]
Guess I should probably fix this. I'll take a look tomorrow @TraGicCode 👍

**Comment by OlafFlorian** [comment]
the resource is missing in 
lib/puppet/type/splunk_config.rb

**Comment by vandelin586** [comment]
The error I am getting
"Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'splunkforwarder_server'"

**Comment by alexcreek** [comment]
yea it doesn't exist. there's a splunk_server but not a splunkforwarder_server :(

**Comment by OlafFlorian** [comment]
the config-file-resources, splunkforwarder_output, _input, _web and so on are defined in lib/puppet/type/splunk_config.rb, currently splunkforwarder_server is missing there.
Until this is fixed here you could add them manually.

**Comment by alexcreek** [comment]
here ya go https://github.com/voxpupuli/puppet-splunk/pull/126
