### ISSUE TITLE
Unable to get basic Splunk server running

### ISSUE THREAD

**Issue by john275** [voxpupuli/puppet-splunk#155]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.5.1 (vagrant) 4.10.8 (vmware)
- Ruby: 2.1.9p490
- Distribution: Ubuntu 16.04 LTS
- Module version: v7.0.0

## How to reproduce (e.g Puppet code you use)
class mailonline::splunk2 {

  class { '::splunk::params':
    version      => '6.6.3',
    src_root     => 'http://somebucket.s3-website-eu-west-1.amazonaws.com',
    splunkd_port => '8089',
  }

include ::splunk

}
## What are you seeing
Error: Failed to apply catalog: no parameter named 'section'

## What behaviour did you expect instead
Notice: Applied catalog in n.nn seconds

## Output log
Info: Using configured environment 'env'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Warning: Creating splunk_index via Puppet.newtype is deprecated and will be removed in a future release. Use Puppet::Type.newtype instead.
   (at /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:162:in `newtype')
Info: Caching catalog for <hostname>
Error: Failed to apply catalog: no parameter named 'section'

## Any additional information you'd like to impart
Tried it on v6.3.1 as well same issue

**Comment by vandelin586** [comment]
Do you need the build number in there as well?

**Comment by john275** [comment]
Unfortunately not, but good spot vandelin586, I was hopeful that would be it. I have my deb package at:

http://somebucket.s3-website-eu-west-1.amazonaws.com/products/splunk/releases/6.6.3/linux/splunk-6.6.3-e21ee54bc796-linux-2.6-amd64.deb

My Manifest now looks like:

class mailonline::splunk2 {

  class { '::splunk::params':
    version      => '6.6.3',
    build        => 'e21ee54bc796',
    src_root     => 'http://somebucket.s3-website-eu-west-1.amazonaws.com',
    splunkd_port => '8089',
  }

include ::splunk

}

I tried adding server as per your class but that still made no difference, but thanks for the suggestion.

**Comment by john275** [comment]
Also had a look through splunk::params, the notes and code suggests the path to the .deb package should be @ .../splunk/linux/splunk-6.6.3-e21ee54bc796-linux-2.6-amd64.deb, tried adding my .deb to that location but still no change in the error *Error: Failed to apply catalog: no parameter named 'section'*

**Comment by john275** [comment]
I get further misery when trying to use puppet:///... as a src_root:

Error: Failed to apply catalog: Parameter source failed on Archive[/opt/staging/splunk/splunk-6.6.3-e21ee54bc796-linux-2.6-amd64.deb]: invalid source url: puppet:///modules/mymodule/mypath/splunk/linux/splunk-6.6.3-e21ee54bc796-linux-2.6-amd64.deb at /etc/puppetlabs/code/environments/myenv/modules-thirdparty/splunk/manifests/init.pp:84 

Using:

  class { '::splunk::params':
    version      => '6.6.3',
    build        => 'e21ee54bc796',
    src_root     => 'puppet:///modules/mymodule/mypath',
  }

But can confirm file residing in correct place by running the below on puppet server:
puppet apply -e "file {'/tmp/wibble': source => 'puppet:///modules/mymodule/mypath/splunk/linux/splunk-6.6.3-e21ee54bc796-linux-2.6-amd64.deb',}" --environment myenv
Notice: Compiled catalog for myserver in environment myenv in 0.07 seconds
Notice: /Stage[main]/Main/File[/tmp/wibble]/ensure: defined content as '{md5}dabf657da3f7c4023c07f25857db65c4'
Notice: Applied catalog in 2.62 seconds

**Comment by john275** [comment]
Still interested in getting this working, if there are any pointers I'd much appreciate.

**Comment by john275** [comment]
Update:
With help of a colleague, we updated our Puppetfile to honour the version requirements in metadata.json - However we still had issues, this was resolved by removing some in-house written ruby splunk library modules, that we presumed the names were colliding.
