### ISSUE TITLE
Splunk_serverclass exists but is not documented

### ISSUE THREAD

**Issue by rbclark** [voxpupuli/puppet-splunk#218]
## What are you seeing

In the README for this project there is no mention of the `splunk_serverclass` type however such a type exists.

## What behaviour did you expect instead

The README to include documentation for all types.

**Comment by bastelfreak** [comment]
Hi @rbclark, thanks for raising this issue. Are you interested in providing a PR to update the docs?

**Comment by rbclark** [comment]
Yep I've fixed it in the referenced issue.
