### ISSUE TITLE
Error with ini_file autoload

### ISSUE THREAD

**Issue by bc-bjoern** [voxpupuli/puppet-splunk#239]
Hey, 

we got this error: 

`
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/splunk_config: Could not autoload puppet/provider/splunk_metadata/ini_setting: no such file to load -- puppet/util/ini_file (file: /etc/puppetlabs/code/environments/x/external_modules/splunk/manifests/params.pp, line: 306, column: 3) on node ...
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
`

- inifile Version v3.0.0 
- translate Version 1.2.0
- stdlib Version 5.2.0
- splunk Version master

Got no clue why this happens. Any advice?

**Comment by WembleyFord2** [comment]
Yup - you're on too new a version of inifile - try using version 2.5.0 - the dependency page says versions < 3.0
Dave

**Comment by bc-bjoern** [comment]
Ahhh you made my day!
