### ISSUE TITLE
How to point splunk forwarder to a deploymentserver which listening on 8089? 

### ISSUE THREAD

**Issue by Balajiswz** [voxpupuli/puppet-splunk#248]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)
Not much example to use apart from 
Default value: $splunk::params::version

purge_deploymentclient

## What are you seeing
The documentation talks about purge_deploymentclient

## What behaviour did you expect instead
To see how can we set the splunk universal forwarder to do the deploy-poll on 8089 port

**Comment by nick-markowski** [comment]
Hey, @Balajiswz we can incorporate some additional documentation with the next release.  I think what you're looking for is along the lines of:

```
splunkforwarder_deploymentclient { 'target_uri':
  section => 'target-broker:deploymentServer',
  setting => 'targetUri',
  value => <your.server.ip>:8089, #adjust as needed
}
```

**Comment by Balajiswz** [comment]
Thanks @nick-markowski !! That is what I am looking for. In my customized puppet module, I used the above, as a separate resource. Should I use them as hash parameters in forwarders?
I used like below and didn't work,

`<class my_splunk ( $splunk_version          = undef,
                        $splunk_build            = undef,
                        $splunk_src_root         = 'https://download.splunk.com',
                        $splunk_default_user     = 'splunk',
                        $deployment_server       = 'x.x.x.x',
) {

    class { '::splunk::params':
      version     => $splunk_version,
      build       => $splunk_build,
      src_root    => $splunk_src_root,
      splunk_user => $splunk_default_user,
    }

    class { '::splunk::forwarder':
      package_ensure => 'latest',
    }

    splunk::splunkforwarder_deploymentclient { 'deployment-server Target URI':
      section => 'target-broker:deploymentServer',
      setting => 'targetUri',
      value   => "$deployment_server:8089",
    }
}>`
