### ISSUE TITLE
Facter splunk version

### ISSUE THREAD

**Issue by bc-bjoern** [voxpupuli/puppet-splunk#280]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6
- Ruby: 2.0.0p648
- Distribution: CentOS Linux release 7.7.1908 (Core)
- Module version: v8.0.0

## How to reproduce (e.g Puppet code you use)

puppet agent -t --debug

## What are you seeing

Puppet run hangs on the fact: 

`Debug: Facter: fact "splunk_version" resolved to null and will not be added.
Debug: Facter: executing command: /bin/sh -c /opt/splunkforwarder/bin/splunk --version
^CNotice: Caught INT; exiting
`

When i execute the command manually, I have to accept the license. 

`
Do you agree with this license? [y/n]: y

This appears to be your first time running this version of Splunk.

Splunk software must create an administrator account during startup. Otherwise, you cannot log in.
Create credentials for the administrator account.
Characters do not appear on the screen when you type in credentials.

Please enter an administrator username: 
`

## What behaviour did you expect instead

How to work around this showstopper?

**Comment by wcooley** [comment]
This is the same as #238. You can manually accept the license (and possibly upgrade migration) with `bin/splunk status --accept-license --no-prompt --answer-yes`.

**Comment by root-expert** [comment]
This was fixed in 5778673eee9fa92453fda520cfafe23651abaac1
