### ISSUE TITLE
child class splunk::forwarder::password::seed has a typo in the fact

### ISSUE THREAD

**Issue by jose-lmax** [voxpupuli/puppet-splunk#289]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.7.1-1
- Ruby: 1.8.7.374-4 
- Distribution: centos 6
- Module version: 8.0.1-rc0

## How to reproduce (e.g Puppet code you use)
set the following in hiera
splunk::forwarder::manage_password: false
splunk::forwarder::seed_password: true

## What are you seeing
puppet deletes /opt/splunkforwarder/etc/passwd
puppet creates /opt/splunkforwarder/etc/system/local/user-seed.conf
It happens every run, hence it restarts splunk

## What behaviour did you expect instead
To do the actions above only the first time, after do nothing.

## Any additional information you'd like to impart
Possible to fix with this PR: https://github.com/voxpupuli/puppet-splunk/pull/288

**Comment by ekohl** [comment]
Since #288 was merged I'm closing this.
