### ISSUE TITLE
inheritence and version overrides

### ISSUE THREAD

**Issue by nvalentine-puppetlabs** [voxpupuli/puppet-splunk#3]
Heads up... I've not yet tracked down all of these issues here but if you classify as such:

    class { 'splunk::linux_forwarder':
      splunk_ver = <some non-default value>,
    }

you won't get the version specified due to the way the default version is specified in params and set in the implementation class via inheritance. I believe that the use of way inheritance is used in this module may mean there are other similar issues.

**Comment by crayfishx** [comment]
This issue hasn't had any updates in nearly 3 years and nothing seems to refer to a remaining problem so I'm going to mark this as closed... if there is still an issue around this please feel free to re-open and add more up to date details.... thanks.
