### ISSUE TITLE
splunk::enterprise - "has no parameter" manage_net_tools

### ISSUE THREAD

**Issue by roscokhan** [voxpupuli/puppet-splunk#327]
- Puppet: 6.3.1

- Ruby: 2.5.9p229 (2021-04-05 revision 67939)

- Distribution: RHEL8.4

- Module version: latest

## How to reproduce (e.g Puppet code you use)

```
   class { 'splunk::enterprise':

      package_ensure => latest,
      manage_password => true,
      enterprise_homedir => '/mnt/services/splunk/enterprise',
      splunk_user => 'splunk',
      password_content => '[PASSWORD HASH]',
      manage_net_tools => false,

   }
```

Also tried manage_net-tools (syntax error), manage_nettools (

## What are you seeing

Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Splunk::Enterprise]: has no parameter named 'manage_net_tools'

## What behaviour did you expect instead

manage_net_tools => false accepted and results in net-tools package assumed managed elsewhere.

## Output log

As per above

## Any additional information you'd like to impart

Can't think of anything directly relevant at this point...

**Comment by kenyon** [comment]
The error message is correct. `manage_net_tools` is a parameter of the `splunk::params` class. So you'll want to set the value with hiera, like this:

```yaml
splunk::params::manage_net_tools: true
```

**Comment by roscokhan** [comment]
Hi Keynon,

OK - in that case, the documentation needs a tweak, as it lists manage_net_tools as a member of the enterprise class.


Many thanks,


Ross
________________________________
