### ISSUE TITLE
Question on monitoring journald

### ISSUE THREAD

**Issue by Tamerz** [voxpupuli/puppet-splunk#366]
Hello. I'm trying to understand how to start monitoring journald using this module with the forwarder.

The official instructions are here: https://docs.splunk.com/Documentation/Splunk/9.1.2/Data/CollecteventsfromJournalD

The forwarder installs a default app in `splunkforwarder/etc/apps/journald_input`

How do I use that with this module? I see there is a `splunk::addon` class, but that seems to only apply to installing new apps. Is it possible to use it with the built in apps that came with the base installation?

Thank you.

**Comment by siegy22** [comment]
Yes you can, there's a parameter for all the splunk resource types called `context` ([see here](https://github.com/voxpupuli/puppet-splunk/blob/master/lib/puppet_x/puppetlabs/splunk/type.rb#L58))

So what you can do is for example define:

```puppet
@splunkforwarder_input { 'realmd':
  section => '[monitor:///var/log/foo]',
  setting => 'index',
  value => 'foo',
  context => 'apps/journald_input'
}
```

Which will do the following:

```ini
# $SPLUNK_HOME/etc/apps/journald_input/inputs.conf

[monitor:///var/log/foo]
index=foo
```

**Comment by Tamerz** [comment]
Thank you.
