### ISSUE TITLE
Invalid parameter key_val_separator

### ISSUE THREAD

**Issue by ITBlogger** [voxpupuli/puppet-splunk#4]
Hello SE Team,

I'm using this new version of your module and getting the following very unhelpful, unspecific errors.

     Error: /Stage[main]/Splunk::Forwarder/Splunkforwarder_output[tcpout_defaultgroup]:   Could not evaluate: Invalid parameter key_val_separator(:key_val_separator)
     Error: /Stage[main]/Splunk::Forwarder/Splunkforwarder_input[default_host]: Could not evaluate: Invalid parameter key_val_separator(:key_val_separator)
     Error: /Stage[main]/Splunk::Forwarder/Splunkforwarder_output[defaultgroup_server]: Could not evaluate: Invalid parameter key_val_separator(:key_val_separator)
     Error: /Stage[main]/Splunk::Platform::Posix/Splunkforwarder_input[monitor_varlog]: Could not evaluate: Invalid parameter key_val_separator(:key_val_separator)

I've checked my parameters and looked over your module and can't find anything glaringly obvious that would be causing this.

A Google search doesn't really show much. Hope you can help.

Thanks,

Alex

**Comment by crayfishx** [comment]
This issue hasn't had any updates in nearly 3 years so I'm going to consider this legacy and fixed and close... if that's not the case then please feel free to re-open the issue after testing against the latest version.  Thanks
