### ISSUE TITLE
module doesn't notify splunk restart when changing an input

### ISSUE THREAD

**Issue by adamstrawson** [voxpupuli/puppet-splunk#63]
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 3.8.5
- Ruby: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
- Distribution: Ubuntu 16.04.1 LTS
- Module version: 4.0.0
### How to reproduce

```
class { '::splunk::forwarder': }

@splunkforwarder_input { 'source_type_example':
    section => "monitor://$logs_path/*.log",
    setting => 'sourcetype',
    value   => $name,
    tag     => "splunk_forwarder"
  }
```
### What are you seeing

When applying a change to an instance that has already had puppet applied to it (eg. splunkforwarder already installed, then editing 'source_type_example' and running again), splunkforwarder is not restarted.
### What behaviour did you expect instead

When making a chance to the resource type for splunk, splunk should be restarted
### Output log

```
Notice: /Stage[main]/Splunk::Forwarder/File[/opt/splunkforwarder/etc/system/local/inputs.conf]/ensure: created
Notice: /Stage[main]/Splunk::Forwarder/Splunkforwarder_input[default_host]/ensure: created
```

No mention of a restart in the output, when running `splunk list monitors` the new input doesn't exist. Once I manually restart splunk `splunk restart`, the monitor then shows.

**Comment by Vincent--** [comment]
Seems to work properly in version 5.0.2
Might be due to this fix: https://github.com/voxpupuli/puppet-splunk/commit/f520a1802d586c8f95cac2c48070647eb207318f

Could you try again with this version of the puppet-splunk module?

**Comment by crayfishx** [comment]
Yes, I think this was the exact problem that #50 fixed

**Comment by adamstrawson** [comment]
Perfect, I'll test this tomorrow when I'm back in the office 👍

**Comment by adamstrawson** [comment]
Version 5.0.2 does indeed fix this issue.  Thanks!
