### ISSUE TITLE
Need a `splunkforwarder_input` defined resource type

### ISSUE THREAD

**Issue by zmeekins** [voxpupuli/puppet-splunk#75]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: `2016.4.0`
- Ruby: `ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]`
- Distribution: OEL 6/7
- Module version: `ce5b15ad5993cae6b72739d9f05f656ebfc5347c`

## What are you seeing

There are defined resource types for all of the other `splunkforwarder_*` configurations. However, we need one that handles limits and is placed in `/opt/splunkforwarder/etc/system/local/limits.conf`. It appears this one has just been missed.

## What behaviour did you expect instead

It should behave exactly the same as all of the other `splunkforwarder_*` defined resource types.

## Any additional information you'd like to impart

The other defined resource types work great.

**Comment by TraGicCode** [comment]
This actually is implemented now.

https://github.com/voxpupuli/puppet-splunk/blob/master/lib/puppet/type/splunk_limits.rb
https://github.com/voxpupuli/puppet-splunk/blob/master/lib/puppet/type/splunkforwarder_limits.rb
