### ISSUE TITLE
Erro deploying Splunk both Server and Forwarder

### ISSUE THREAD

**Issue by alfredodeluca** [voxpupuli/puppet-splunk#76]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.6
- Ruby: ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
- Distribution: CentOS release 6.7 (Final)
- Module version: 5.0.2

## What are you seeing
Error: Could not autoload puppet/type/splunk_config: /var/lib/puppet/lib/puppet/type/splunk_config.rb:7: syntax error, unexpected ':', expecting ')'
  newparam(:name, namevar: true) do
                          ^
/var/lib/puppet/lib/puppet/type/splunk_config.rb:128: syntax error, unexpected ':', expecting ')'
        name: instance.name,
             ^
/var/lib/puppet/lib/puppet/type/splunk_config.rb:129: syntax error, unexpected ':', expecting '='
        section: instance[:section],
                ^
/var/lib/puppet/lib/puppet/type/splunk_config.rb:130: syntax error, unexpected ':', expecting '='
        setting: instance[:setting],
                ^
/var/lib/puppet/lib/puppet/type/splunk_config.rb:131: syntax error, unexpected kENSURE, expecting '='
        ensure: :absent
              ^
/var/lib/puppet/lib/puppet/type/splunk_config.rb:132: syntax error, unexpected ')', expecting kEND
Error: Could not retrieve catalog from remote server: Could not intern from text/pson: Could not autoload puppet/type/splunk_config: /var/lib/puppet/lib/puppet/type/splunk_config.rb:7: syntax error, unexpected ':', expecting ')'
  newparam(:name, namevar: true) do
                          ^
/var/lib/puppet/lib/puppet/type/splunk_config.rb:128: syntax error, unexpected ':', expecting ')'
        name: instance.name,
             ^
/var/lib/puppet/lib/puppet/type/splunk_config.rb:129: syntax error, unexpected ':', expecting '='
        section: instance[:section],
                ^
/var/lib/puppet/lib/puppet/type/splunk_config.rb:130: syntax error, unexpected ':', expecting '='
        setting: instance[:setting],
                ^
/var/lib/puppet/lib/puppet/type/splunk_config.rb:131: syntax error, unexpected kENSURE, expecting '='
        ensure: :absent
              ^
/var/lib/puppet/lib/puppet/type/splunk_config.rb:132: syntax error, unexpected ')', expecting kEND
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

## What behaviour did you expect instead
To be installed smoothly 

## Any additional information you'd like to impart
I have installed the same module on both centos 6 and 7 but with different ruby version (2.1) and it worked fine.

**Comment by petems** [comment]
This is an issue with CentOS 6 shipping with Ruby 1.8.7:

https://github.com/voxpupuli/plumbing/issues/36

**Comment by alfredodeluca** [comment]
Thanks Peter. So can I upgrade ruby on the puppet agent without upgrading puppet itself?

**Comment by bastelfreak** [comment]
Puppet3.8 works with ruby 2.1 and older. You can upgrade ruby without upgrading puppet, but this is probably also painful on centos. Puppet3 is end of life by the end of this month, I recommend to upgrade your puppet version. Puppet4 ships with his own ruby version.

**Comment by TraGicCode** [comment]
Closing this since we don't support puppet 3 on this module based on the metadata.json
