### ISSUE TITLE
Support .conf files in non-standard locations

### ISSUE THREAD

**Issue by kpschuck** [voxpupuli/puppet-splunk#88]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: All versions
- Distribution: All distributions
- Module version: All versions

## How to reproduce (e.g Puppet code you use)
```puppet
splunk_props { 'useless title':
  path    => '/opt/splunk/etc/master-apps/_cluster/local',  # <-- would like to be able to do this
  section => 'default',
  setting => 'defaultGroup',
  value   => 'splunk_9777',
}
```

## What are you seeing
The resource types have hardcoded paths to the `.conf` files and do not allow for specifying a path. 

## What behaviour did you expect instead
Allowing the path to be specified on a per-resource basis would allow for management of index and search head clusters.

Specifically, I would like to be able to manage the index cluster config files located at `/opt/splunk/etc/master-apps/_cluster/local` on the cluster master.

## Any additional information you'd like to impart
Is this something that this module could support? If so, what would be the recommended way to implement this? 

I've gotten this working by declaring additional resource types (`splunkmaster_indexes` and `splunkmaster_inputs`) but it feels forced. I have not been successful in implementing a `path` property on the base type since it seems to be a limitation of `puppetlabs-inifile`.

**Comment by kpschuck** [comment]
Looks like I missed https://github.com/voxpupuli/puppet-splunk/pull/87. Closing this in favor of discussion on the PR.

**Comment by edt82** [comment]
Hi, trying to use this new setting as so in heira:

```
  myindex_homePath:
    section: myindex
    setting: homePath
    value: $SPLUNK_DB/myindex/db
    context: master-apps/_cluster/local

```
but getting error: no parameter named 'context' 
Confirmed i have pulled this commit.
Have you been able to use the context setting?
Hoping there's going to be an update to the readme soon.
