### ISSUE TITLE
Evaluation Error: Unknown variable: 'splunk::params::forwarder_install_options'

### ISSUE THREAD

**Issue by shadow999** [voxpupuli/puppet-splunk#97]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.9.2
- Ruby: 2.3.1
- OS: Ubuntu 16.04 
- Module version: 5.1.0

## How to reproduce (e.g Puppet code you use)
```
  class { '::splunk::params':
    server   => hiera(my_splunk_server),
    version  => hiera(my_splunk_version),
    build    => hiera(my_splunk_build),
    src_root => hiera(my_splunk_src_root),
  }

  class { '::splunk::forwarder':
  }
```

## What are you seeing
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown variable: 'splunk::params::forwarder_install_options'.

## What behaviour did you expect instead
Compile without error

## Any additional information you'd like to impart
Need to put `forwarder_install_options` as class parameter for `params` and assign `undef` as default value or assign `undef` for different kernels other than Windows to avoid this compile error.

**Comment by bastelfreak** [comment]
Hi @shadow999, thanks for the PR. Are you able to provide a Pull Request for this? Feel free to joint #voxpupuli on freenode (IRC) if you have any questions. We are around 24/7.

**Comment by shadow999** [comment]
https://github.com/voxpupuli/puppet-splunk/pull/99
